# Generated by Django 5.1.2 on 2024-12-11 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj', '0003_alter_journey_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='PinnedLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tj.journey')),
            ],
            options={
                'db_table': 'tj_pinnedlocation',
            },
        ),
    ]
