# Generated by Django 5.1.2 on 2024-12-11 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj', '0004_alter_journey_options_pinnedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedlocation',
            name='uuid',
            field=models.ForeignKey(db_column='uuid', on_delete=django.db.models.deletion.CASCADE, to='tj.journey'),
        ),
        migrations.AlterModelTable(
            name='journey',
            table='tj_journey',
        ),
    ]
